name = "tech-feeds"
compatibility_date = "2024-11-06"
pages_build_output_dir = "./dist"
compatibility_flags = [ "nodejs_compat" ]

[[kv_namespaces]]
binding = "KV"
id = "e287a310d3bc47909598ac323929a155"

[triggers]
crons = ["0 * * * *"]